### ISSUE TITLE
spec: update syntax to forbid private method in object literal

### ISSUE THREAD

**Issue by JLHwung** [tc39/proposal-private-methods#78]
As of July 2020, current spec changes

```
MethodDefinition[Yield, Await]:
  PropertyName[?Yield, ?Await] ( UniqueFormalParameters[~Yield, ~Await] ) { FunctionBody[~Yield, ~Await] }
```
to
```
MethodDefinition[Yield, Await]:
  ClassElementName[?Yield, ?Await] ( UniqueFormalParameters[~Yield, ~Await] ) { FunctionBody[~Yield, ~Await] }
```

However `MethodDefinition` is also used in `ObjectLiteral` via [`PropertyDefinition`](https://tc39.es/ecma262/#prod-PropertyDefinition). So according to the spec, the following usage becomes valid

```js
class C {
  #a() {
    return { #a(){ return 42 } };
  }
}
```
Correct me if I am wrong, but I don't see any early error for `ObjectLiteral => MethodDefinition => PrivateIdentifier` productions in this spec. I believe this is an unwanted side-effect.

I suggest we add a new `ClassMethodDefinition` productions.

**Comment by caiolima** [comment]
Thank you very much for the report.

I checked current [spec](https://arai-a.github.io/ecma262-compare/?pr=1668&id=sec-object-initializer-static-semantics-early-errors), and there's an early error on `PropertyDefinition : MethodDefinition` where `PrivateBoundIdentifiers of MethodDefinition is not empty`. This seems to be covering the case you are worried about. I'm closing this issue, since the bug seems to be resolved. Let me now otherwise.
