### ISSUE TITLE
What does #constructor leave for?

### ISSUE THREAD

**Issue by LongTengDao** [tc39/proposal-private-methods#86]

**Comment by ljharb** [comment]
Can you restate your question? I'm not sure what you're asking.

**Comment by LongTengDao** [comment]
> Can you restate your question? I'm not sure what you're asking.

Oh, thank you!

I mean, I found the spect treat `#constructor` as a special name, it's limited to use when I try in my code; but currently, the spec didn't say what purpose it leave for in the future.

I want to know what it leave for, when design it.

**Comment by ljharb** [comment]
I don't believe it was set aside for future purposes - my recollection is that `constructor;` was reserved permanently as a private field to avoid confusion between `constructor() {}` and an own `constructor` property; and that similarly, `#constructor;` and `#constructor() {}` were banned as well.

If this recollection isn't accurate, hopefully someone else can clarify :-)

**Comment by erights** [comment]
> If this recollection isn't accurate, hopefully someone else can clarify :-)

Not accurate ;)

A possible future use of `#constructor() {}` is a class whose constructor (the class itself) is not available from instances via `.constructor`. This would allow more direct expression of patterns, such as allowed for `WeakRef`, where there is no `.constructor` property on the prototype pointing back at the class; in order to deny the class to those who are given instances.

As SES has shaped up, we are no longer of the opinion that this is the best pattern for denying that access. The problem is that this absence means that `instance.constructor` will obtain the inherited `Object` constructor instead, which is just confusing. Rather, SES (and therefore TC53 and Moddable) use the inert constructor pattern instead.

Thus, this possible future use is now less likely than some way to express the inert constructor pattern in class syntax. But we don't yet have a proposed syntax for that. It could have been done with some versions of decorators, but I don't know about the current state of decorator proposals.
